kkevsekk1/AutoX

- Readme.md
- app/src/main/java/org/autojs/autojs/pluginclient/DevPluginResponseHandler.java
> Feature market

- autojs/src/main/java/com/stardust/autojs/util/FloatingPermission.java
fix floating window  permission check  on miui
> fix: floating window  permission check  on miui

- .github/workflows/android.yml
- .gitignore
- app/build.gradle
- inrt/build.gradle
- inrt/src/main/java/com/stardust/auojs/inrt/SplashActivity.kt
> Feature test ci

- app/src/main/java/org/autojs/autojs/ui/explorer/ExplorerView.java
- app/src/main/java/org/autojs/autojs/ui/project/BuildActivity.java
- app/src/main/java/org/autojs/autojs/ui/project/ProjectConfigActivity.java
- autojs/src/main/java/com/stardust/autojs/core/ui/inflater/inflaters/BaseViewInflater.java
- project-versions.json
1.调整target及compile版本到29
2.调整应用配置页面:不缓存应用图标
3.修复修改应用配置后,ExplorerChangeEvent UI更新问题
4.打包应用页面支持修改应用配置信息
> 打包时支持修改应用配置，Android 10+自动填充导致闪退问题

- app/src/main/java/org/autojs/autojs/Pref.java
- app/src/main/java/org/autojs/autojs/autojs/build/ApkBuilder.java
- app/src/main/java/org/autojs/autojs/ui/project/BuildActivity.java
- app/src/main/res/layout/activity_build.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
- autojs/src/main/java/com/stardust/autojs/project/LaunchConfig.java
- autojs/src/main/java/com/stardust/autojs/project/ProjectConfig.java
- inrt/src/main/java/com/stardust/auojs/inrt/Pref.java
- inrt/src/main/java/com/stardust/auojs/inrt/launch/AssetsProjectLauncher.kt
模板app稳定模式
打包页面新增主脚本名称、稳定模式、隐藏日志设置
> 打包页面新增主脚本名称、稳定模式、隐藏日志设置

- CHANGELOG.md
- app/src/main/java/org/autojs/autojs/ui/main/market/MarketFragment.java
- autojs/src/main/AndroidManifest.xml
- inrt/build.gradle
- inrt/src/main/java/com/stardust/auojs/inrt/FeatureActivity.java
> Feature js api

- app/src/main/java/org/autojs/autojs/ui/project/BuildActivity.java
> 自动读取project.json中的name

- app/build.gradle
- app/src/main/assets/sample/Webview扩展与游戏编程/AutoX注入webview.js
- app/src/main/assets/sample/Webview扩展与游戏编程/Readme.md
- app/src/main/assets/sample/Webview扩展与游戏编程/game.html
- autojs/build.gradle
- project-versions.json
更新OpenCV到最新的4.5.5，修复图色查找bug。我这边测试正常，不知道你那边能不能运行？
> bug修复及模块更新

- common/src/main/java/com/stardust/util/ScreenMetrics.java
修复屏幕高宽参数获取为0Update ScreenMetrics.java
> 修复屏幕高宽参数获取为0Update ScreenMetrics.java

- autojs/src/main/java/com/baidu/paddle/lite/demo/ocr/OcrResult.java
- autojs/src/main/java/com/baidu/paddle/lite/demo/ocr/Utils.java
- inrt/src/main/java/com/stardust/auojs/inrt/SplashActivity.kt
感觉Rhino 1.7.13版（dev分支，兼容旧脚本）和Rhino 1.7.14版（dev-test分支，gradle7编译，支持更多ES6语法，性能更好）可以同时发布，这样相互之间也不会冲突，用户可以自由选择
> 修复打包问题及优化OCR排序

- app/src/main/assets/sample/Zip压缩与解压/Zip文件压缩与解压.js
- app/src/main/assets/sample/websocket/WebSocket.js
- app/src/main/assets/sample/消息处理(加密、摘要、编码)/base64编码.js
- app/src/main/assets/sample/消息处理(加密、摘要、编码)/加密解密.js
- app/src/main/assets/sample/消息处理(加密、摘要、编码)/消息摘要(MD5, SHA).js
- autojs/src/main/assets/init.js
- autojs/src/main/assets/modules/__$base64__.js
- autojs/src/main/assets/modules/__$crypto__.js
- autojs/src/main/assets/modules/__$zip__.js
- autojs/src/main/assets/modules/__files__.js
- autojs/src/main/assets/modules/__web__.js
- autojs/src/main/java/com/stardust/autojs/core/cypto/Crypto.java
- autojs/src/main/java/com/stardust/autojs/core/web/WebXSocket.java
增加pro的websocket功能[文档地址](https://pro.autojs.org/docs/#/zh-cn/webSocket)
增加pro的zip功能[文档地址](https://pro.autojs.org/docs/#/zh-cn/zip)
增加pro的加解密功能[文档地址](https://pro.autojs.org/docs/#/zh-cn/crypto)
> websocket/base64/crypto/zip js工具包以及代码示例

- inrt/src/main/java/com/stardust/auojs/inrt/SplashActivity.kt
修复没有勾选权限情况打开APP闪退问题（请开启权限后，再运行）
> 修复没有勾选权限情况打开APP闪退问题（请开启权限后，再运行）

- app/build.gradle
- app/src/main/java/org/autojs/autojs/ui/floating/layoutinspector/LayoutHierarchyFloatyWindow.kt
- project-versions.json
> 布局层次悬浮窗由于忘记调整一个地方，导致崩溃，现已修复，并调整版本号为6.0.5

- app/src/main/java/org/autojs/autojs/ui/settings/SettingsActivity.java
- app/src/main/res/raw/licenses_other.md
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
@kkevsekk1 关于 [PR中问题的解释](https://github.com/kkevsekk1/AutoX/pull/365#issuecomment-1186684856)，不是这边不想改，是真的没法像你说的那样改
> @kkevsekk1  怎么又把 [PR](https://github.com/kkevsekk1/AutoX/pull/365) 给关了呢？  @kkevsekk1  @wilinz  问题是没法那样提交啊，那个License组件是专门用于“开放源代码许可”的，只适合添加开源组件，TBS 根本就不是开源组件，又怎么能够强行按开源的方式添加呢？！所以这边也只能另开一个页面了
> 补充 TBS 相关授权许可

- app/src/main/assets/sample/Web扩展与游戏编程/AutoX注入webview.js
> fix(sample): 解决 invoke 不指定回调方法就报错的 bug

- README.md
- README_en.md
[修正下载链接，更新文档](https://github.com/kkevsekk1/AutoX/commit/f3380f664a7f6cb4bc98ada115a1e50bbfc22cc8)
> 修正下载链接，更新文档

- inrt/src/main/res-i18n/values-zh-rCN/strings.xml
- inrt/src/main/res-i18n/values-zh-rTW/strings.xml
- inrt/src/main/res-i18n/values/strings.xml
- 解决 #431 提到的中文双引号错误
- ”软件“繁体中文修正
> Chinese quote

- app/src/main/java/org/autojs/autojs/ui/edit/EditActivity.java
- app/src/main/java/org/autojs/autojs/ui/edit/EditorView.java
- app/src/main/java/org/autojs/autojs/ui/edit/toolbar/NormalToolbarFragment.java
- app/src/main/res/layout/fragment_normal_toolbar.xml
> 修复部分设备编辑界面顶栏按钮重叠

- .github/workflows/stale.yml
所有选项可参考https://github.com/actions/stale
> 自动管理过期lssue和pr

- app/build.gradle.kts
- app/src/main/java/org/autojs/autojs/devplugin/DevPlugin.kt
- autojs/src/main/assets/modules/npm/rxjs/ext.js
- autojs/src/main/java/com/stardust/autojs/runtime/api/Timers.kt
- build.gradle.kts
- codeeditor/build.gradle.kts
- codeeditor/src/main/AndroidManifest.xml
- codeeditor/src/main/java/com/aiselp/autojs/codeeditor/dialogs/LoadDialog.kt
- codeeditor/src/main/java/com/aiselp/autojs/codeeditor/plugins/AppController.kt
- codeeditor/src/main/java/com/aiselp/autojs/codeeditor/plugins/FileSystem.kt
- codeeditor/src/main/java/com/aiselp/autojs/codeeditor/web/EditorAppManager.kt
- codeeditor/src/main/java/com/aiselp/autojs/codeeditor/web/FileHttpServer.kt
- codeeditor/src/main/java/com/aiselp/autojs/codeeditor/web/PluginManager.kt
- codeeditor/src/main/java/com/aiselp/autojs/codeeditor/web/WebEvent.kt
- codeeditor/src/main/res/layout/load.xml
- gradle/libs.versions.toml
新编辑器更新
* 支持在编辑内直接运行脚本
* 支持在设置中配置prettier
* 暗色模式部分样式修复
* 支持打开示例代码中的文件
> 编辑器更新,添加rxjs特有调度器

- autojs/src/main/java/com/stardust/autojs/runtime/ScriptRuntime.java
debug下引入了一个包。在release 下，创建项目-》生成app。这个生成的app会崩溃
> 修复打出的包崩溃问题，release下不启用内存泄漏检测

- app/src/main/assets/sample/MQTT/MQTT连接订阅.js
- common/build.gradle.kts
- common/src/main/AndroidManifest.xml
> feat: mqtt support and demo

- core/network/build.gradle.kts
- gradle/libs.versions.toml
使用 [logback-android](https://github.com/tony19/logback-android)
> 修复 检查更新 打开USB调试 闪退

- app/src/main/java/org/autojs/autojs/ui/timing/TimedTaskSettingActivity.java
- app/src/main/res/layout/activity_edit.xml
- app/src/main/res/layout/activity_tasker_script_edit.xml
> 修复原编辑器，定时任务报错

- app/src/main/java/org/autojs/autojs/Pref.java
- app/src/main/java/org/autojs/autojs/model/script/PathChecker.java
- app/src/main/java/org/autojs/autojs/ui/edit/EditorView.java
- app/src/main/java/org/autojs/autojs/ui/main/MainActivity.kt
- app/src/main/java/org/autojs/autojs/ui/main/scripts/ScriptListFragment.kt
适配android11以上存储权限问题。中文翻译问题不知道原来用的啥框架那么多就先不管了
> Android 11以上外部存储权限适配
